#!/bin/sh
#
# An example hook script to make use of push options.
# The example simply echoes all push options that start with 'echoback='
# and rejects all pushes when the "reject" push option is used.
#
# To enable this hook, rename this file to "pre-receive".

BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(feature|bugfix)\/([a-z]+)\/([0-9]\d)\.([0-9]\d)\.([0-9]\d{3})-([\w\W]+)$"

echo
printf "\n[pre-push-hook] Parsed branch name: %s." "$BRANCH"
echo REGEX=$(echo "$BRANCH" | grep -o -E "$REGEX")
echo

if [[ -z "$REGEX" ]]; then
  echo "Your commit was rejected due to branching name"
  echo "Please rename your branch with '$REGEX"
  exit 1
fi

exit 0
