#!/bin/sh

BRANCH=$(git symbolic-ref --short HEAD)
commit_list=$(git log --oneline HEAD...origin)
REGEX="^(feature|bugfix)\/([a-z]+)\/([0-9]{2}\.[0-9]{2}\.[0-9]{4})-(.{1,30})$"

while read -r commit; do
  commit_message=$(echo "$commit" | cut -d' ' -f2-)
  echo  $commit_message On push
done <<< "$commit_list"

if ! [[ $BRANCH =~ $REGEX ]]; then
  echo "Your commit was rejected due to branching name"
  echo "Please rename your branch with '$REGEX"
  exit 1
fi

exit 0