default_platform(:ios)

platform :ios do

  global_xcode_path = "/Applications/Xcode_14.3.1.app"

  desc "My first fastlane func"
  lane :my_lane do |options|
        scan(
          clean: options[:clean],
          skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
        )
  end

  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end
