name: Pull Requests

on:
  pull_request:
    branches:
      - origin
  workflow_dispatch:

jobs:
  testsing: 
  runs-on: macos-13.3.1
  steps: 
    - uses: actions/checkout@v2

    - name: Cancel Prev Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - uses: sergei-veretennikov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Swift Packages Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-

